server{
    listen 80;
    
    client_max_body_size 50M;  # ✅ allow up to 50 MB uploads

    location /{
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }

    # Proxy API requests to backend container
    location /predict {
        proxy_pass http://backend:8000/predict;
    }
}
