version: "3.9"

services: 
    backend:
      build: ./AWS_storing
      container_name: music-backend
      ports:
        - "8000:8000"
      volumes:
        - ./AWS_storing/artifacts/model:/app/artifacts/model
      restart: always

    frontend:
      build:
        context: ./frontend
      container_name: music-frontend
      ports:
        - "3000:80"
      depends_on:
        - backend
